sudo: required

install:
  - sudo pip install sphinx

script:
  - make clean
  - make html > logfile
  - sed 's/[^0-9]*//g' logfile | tee log2
  - sed '/^\s*$/d' log2 | tee log3
  - NUMBER=$(tail -1 log3)
  - if (( $NUMBER > 3 )); then exit 1; fi

